nemo_gym:
  nemo_gym_root: $NEMO_GYM_ROOT
  uses_reasoning_parser: false
  config_paths:
    - $NEMO_GYM_ROOT/responses_api_models/vllm_model/configs/vllm_model_for_training.yaml
    - $NEMO_GYM_ROOT/resources_servers/math_with_judge/configs/math_with_judge.yaml
